//
// Created by dustyn on 4/17/24.
//

#ifndef UNIXREMOTESHELLSERVER_HANDLECLIENTSHELLSESSION_H
#define UNIXREMOTESHELLSERVER_HANDLECLIENTSHELLSESSION_H
void handle_client(int client_fd);
#endif //UNIXREMOTESHELLSERVER_HANDLECLIENTSHELLSESSION_H
